---
name: build-cyprus-map
on:
  push:
    tags:
      - '*'
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  build-cyprus-map:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fix apt mirrors and update cache
        run: |
          sudo sed -i 's|azure.archive.ubuntu.com|archive.ubuntu.com|g' /etc/apt/sources.list
          sudo apt-get update --fix-missing          
      - name: Install build dependencies
        run: |
          sudo apt-get install -y wget unzip python3 python3-pip python3-matplotlib python3-numpy python3-bs4 python3-pkg-resources python3-gdal osmium-tool openjdk-18-jre-headless
          sudo pip3 install -U matplotlib==3.8.4
          wget -nv http://katze.tfiu.de/projects/phyghtmap/phyghtmap_2.23-1_all.deb -O /tmp/phyghtmap_2.23-1_all.deb
          sudo dpkg -i /tmp/phyghtmap_2.23-1_all.deb
          wget -nv https://www.mkgmap.org.uk/download/mkgmap-latest.zip -O /tmp/mkgmap.zip
          wget -nv https://www.mkgmap.org.uk/download/splitter-latest.zip  -O /tmp/splitter.zip
          unzip /tmp/mkgmap.zip -d /tmp
          unzip /tmp/splitter.zip -d /tmp
          mv /tmp/mkgmap-* /tmp/mkgmap
          mv /tmp/splitter-* /tmp/splitter
          wget -nv https://www.thkukuk.de/osm/data/bounds-latest.zip -O /tmp/mkgmap/bounds-latest.zip
          wget -nv https://www.thkukuk.de/osm/data/sea-latest.zip -O /tmp/mkgmap/sea-latest.zip
      - name: Build
        env:
          USGS_USER: ${{ secrets.USGS_USER }}
          USGS_PASSWORD: ${{ secrets.USGS_PASSWORD }}
        run: ./build.sh
      - name: Get current date
        id: date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Get latest tag
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: output/*.zip
          name: Release ${{ env.DATE }}
          tag: ${{ env.TAG }}
          allowUpdates: true
          replacesArtifacts: true
          body:  |
            Files:
              `Cyprus_OSM.gmap.zip` - for BaseCamp
              `gmapsupp.img` - for device
